### PR TITLE
fixed typos in readme

### PR DESCRIPTION
**Pull request by mueller-ma**

### CODE REVIEW

**Comment by HugoGresse** [comment]
Sorry for the wrong name :/ can you rename the commit because it's not obvious who "my" refer to in the commit message.

**Comment by mueller-ma** [comment]
@HugoGresse I think it got worse

**Comment by HugoGresse** [comment]
haha, you can `git reset --hard origin/master` and change your name and  `git push -f` on your fork. something like this.

**Comment by mueller-ma** [comment]
@HugoGresse Done

**Review by HugoGresse — APPROVED** [review]

**Comment by HugoGresse** [comment]
thanks for this @mueller-ma ! much appreciated.

**Pull request merged**
