### PR TITLE
Add all strings to resources

### PR DESCRIPTION
**Pull request by HugoGresse**

### CODE REVIEW

**Comment by mueller-ma** [comment]
@HugoGresse Should error_general really be quoted?

**Comment by HugoGresse** [comment]
@mueller-ma I don't think so but it should prevent any issue if the error number does not exist.

**Comment by mueller-ma** [comment]
@HugoGresse It's easier for me, when you translate it. Idk how to update my pr. retry = "Wiederholen"

**Comment by HugoGresse** [comment]
sure np. thanks

**Pull request merged**
